### ISSUE TITLE
Cursor lock doesn't work in window mode

### ISSUE THREAD

**Issue by apetresc** [mca64/mca64Launcher#9]
I'm trying to play BW in windowed mode on Windows 8.1. I'm using the latest mca64Launcher, and it works except for one crucial problem: it just ignores the mouse lock option (the one that keeps your cursor locked inside the window so that you can actually scroll the view).

The button to activate it is there, but it doesn't do anything, my cursor happily flies out of the window when I move it to the edge. As you can imagine, this makes playing BW pretty much impossible.

I remember this used to work in Windows 7, and if I use the ICCup launcher for BW I still have this issue, so it must be some strange interaction between Win8 and BW specifically.

Let me know if you want me to try some builds to help diagnose the issue!

**Comment by tostercx** [comment]
I had the same issue - the problem was only if I have windows set to scale applications (125%), if I disable it it works fine. Could you fix it with scaling on newer windows versions?

**Comment by tostercx** [comment]
Hmmm... got it fixed by adding a manifest to StarCraft.exe and setting `<dpiAware>true</dpiAware>`
